#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by jwz@ecust on 17/1/3
import numpy as np
import os


def cont2xyz(contpath, xyzpath):
    with open(contpath, 'r') as con, open(xyzpath, 'w') as xyz:
        content = con.readlines()
        latt_mat = np.zeros((3, 3))
        _abc = [_.strip() for _ in content[2:5]]
        for i in range(3):
            latt_mat[i] = np.array([ttt for ttt in _abc[i].split('  ') if ttt], dtype=np.float)
        abc = np.zeros(3)
        for i in range(3):
            abc[i] = np.linalg.norm(latt_mat[i])
        _atom_info = content[5:7]
        types = [i for i in _atom_info[0].strip().split('  ') if i]
        numbers = [int(i) for i in _atom_info[1].strip().split('  ') if i]
        total = sum(numbers)
        xyz.write(' '*8 + str(total) + '\n')
        xyz.write('generated by python\n')
        atoms = dict(zip(types, numbers))
        # print atoms
        coordates = content[9:9+total]
        coordates = [i.strip().split('T')[0].strip() for i in coordates]
        coordates = np.array([[m for m in i.split(' ') if m] for i in coordates], dtype=np.float)
        coordates = coordates*abc.T
        s = 0
        for atom in types:
            for number in range(atoms[atom]):
                nnn = str(coordates[s][0]).rjust(20) + str(coordates[s][1]).rjust(20) + str(coordates[s][2]).rjust(20)
                line = atom.ljust(8)+nnn.rjust(60)
                xyz.write(line+'\n')
                s += 1



contcar_path = '/Volumes/WD/data/NiP_data/surface/contcar'
contcars = os.listdir(contcar_path)
for sss in contcars:
    contpath = contcar_path + '/' + sss
    xyzpath = contpath + '.xyz'
    cont2xyz(contpath, xyzpath)
