#!/bin/sh
na=$1
nb=$2
if [ $# -eq 0 ];then
  echo "Please run with a district : from a to b."
  exit;
elif [ $# -eq 1 ];then
  nb=0
fi
if [ `echo "$na > $nb" | bc` -eq 1 ];then
  nc=$nb
  nb=$na
  na=$nc
fi

outfile=result
name0=`ls | grep DOS.SUM | sed -n '1'p`
natoms=`echo $name0 | awk -F. '{print $NF}'`
nl=`cat $name0 | awk '{print ($1>='$na')&&($1<='$nb')}' |  grep -n 1 | awk -F: '{print $1}'`
if [ -z "$nl" ];then
  echo "can't find the district from $na to $nb ..."
  exit
fi
nstart=`echo $nl | awk '{print $1}'`
nend=`echo $nl | awk '{print $NF}'`
echo "     num       s       p       d     sum" > $outfile
sed -n ''$nstart','$nend'p' $name0 | awk '{print ($2>0?$2:-$2),($3>0?$3:-$3),($4>0?$4:-$4),($5>0?$5:-$5),($6>0?$6:-$6),($7>0?$7:-$7)}' \
  | awk '{a+=$1+$2;b+=$3+$4;c+=$5+$6}END{print a,b,c,a+b+c}' >tempy0
if [ "`awk '{print $NF==0}' tempy0`" -eq 1 ];then
  echo "the district from $na to $nb has nothing ..."
  exit
fi
cat tempy0 | awk '{printf "%8s%8.2f%8.2f%8.2f%8.2f\n","all",100*$1/$4,100*$2/$4,100*$3/$4,100}'>> $outfile
for i in `seq 1 $natoms`
do
  namei="DOS"$i
  sed -n ''$nstart','$nend'p' $namei | awk '{print ($2>0?$2:-$2),($3>0?$3:-$3),($4>0?$4:-$4),($5>0?$5:-$5),($6>0?$6:-$6),($7>0?$7:-$7)}' \
  | awk '{a+=$1+$2;b+=$3+$4;c+=$5+$6}END{print a,b,c,a+b+c}'>tempyi
  paste -d" " tempyi tempy0 | awk '{printf "%8s%8.2f%8.2f%8.2f%8.2f\n",'$i',100*$1/$5,100*$2/$6,100*$3/$7,100*$4/$8}'>>$outfile
done
rm -f tempy*
echo "from $na to $nb :"
cat $outfile
